excluded:
  - Pods
  - vendor
  - archives
  - derived_data
  - derived_data_tests
  - Luca/Secrets.generated.swift

disabled_rules: # rule identifiers turned on by default to exclude from running
  - identifier_name
  - unused_setter_value
  - cyclomatic_complexity
  
line_length:
    warning: 200
    error: 300
    ignores_comments: true

type_name:
    max_length:
        warning: 45
        error: 60
    min_length:
        warning: 1
        
file_length:
    warning: 450
    error: 700
