# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Luca.xcodeproj")
    build_app(workspace: "Luca.xcworkspace", scheme: "Luca")
    # upload_to_testflight
  end
end
